### ISSUE TITLE
Not working in latest version ((( Idea 2022.3 Beta (Ultimate Edition)

### ISSUE THREAD

**Issue by vruzin** [Noorts/Toggler#21]
Not working in latest version ((( Idea 2022.3 Beta (Ultimate Edition)

**Comment by vruzin** [comment]
IntelliJ IDEA 2022.3 Beta (Ultimate Edition)
Build #IU-223.7401.7, built on November 2, 2022
Runtime version: 17.0.5+1-b653.6 amd64
Kotlin: 223-1.7.20-release-201-IJ7401.7

**Comment by Noorts** [comment]
Hey @vruzin, thanks for the heads up!

I just made the necessary changes and pushed a new update to the marketplace.

The fix (v1.2.11) is available [here](https://github.com/Noorts/Toggler/releases/tag/v1.2.11) as a release and will be available on the marketplace and in your IDE once JetBrains approves the update (usually two business days).

Feel free to let me know if you have any further feedback.

**Comment by vruzin** [comment]
Perfect!!! Thank you!!!!
Thanks a lot!!! Great plugin! Thank you for such a quick response and help!!!
