### ISSUE TITLE
Add reverse toggle action

### ISSUE THREAD

**Issue by Noorts** [Noorts/Toggler#56]
As requested by a [review](https://plugins.jetbrains.com/plugin/16166-toggler/reviews#review=96108) on the JetBrains marketplace.
> It would be beneficial to include shortcuts for shuffling items up and down. When dealing with numerous suggestions, navigating through them becomes more convenient by moving both upward and downward.

This could be implemented as a simple _reverse_ toggle action.

The current shortcut for the toggle action is `Ctrl/Cmd+Shift+X`. Using an additional modifier (e.g., `Alt/Opt`) for the reverse action might make it cumbersome to activate. However, I'll likely go with that for now anyway (so it will be `Ctrl/Cmd+Shift+Alt/Opt+X`). Better keybind suggestions (which do not conflict with the default IDE's keybinds) are very much welcome!

**Comment by Noorts** [comment]
Implemented as per:
- #58 

The new update is available [here](https://github.com/Noorts/Toggler/releases/tag/v1.3.0) as a release, and will be released after approval on the marketplace in about 2 business days.

**Comment by timurproko-archive** [comment]
Thank you for undertaking this task. It greatly streamlines the use of the dictionary, and I am extensively utilizing it. I'm really pleased that you took the initiative.
