### ISSUE TITLE
How to set up the [ { symbols?

### ISSUE THREAD

**Issue by holysheng** [Noorts/Toggler#78]
["[]", "{}"],
  ["(", ")"],
  ["[", "]"],
  ["{", "}"],
  ["'", "\"", "`"],

**Comment by Noorts** [comment]
Hello @holysheng! Thanks for reaching out.

Unfortunately, as described [here](https://github.com/Noorts/Toggler?tab=readme-ov-file#configuration), those symbols are boundary characters used by Toggler internally (to detect word boundaries), thus those symbols cannot be used.

During development I was (and still am) not aware of other ways to perform boundary detection without disallowing the use of those symbols in toggles.

Edit: I recall that there was functionality available to find the boundary of words in the editor API, but it did not work exactly as I wanted it to, so I built my own logic for it.
