### ISSUE TITLE
Add feature to have configuration per language

### ISSUE THREAD

**Issue by timurproko-archive** [Noorts/Toggler#83]
The Togler plugin has been incredibly useful and has saved me a significant amount of time. However, one feature that I believe would greatly enhance its functionality is the ability to configure settings on a per-filetype basis.

For example:

In C#, I would like to define toggles for types like:
["void", "bool", "int", "float", "double", "string"]
In HLSL, I would prefer toggles for:
["float", "float1", "float2", "float3", "float4"]
This level of customization would make the plugin even more versatile and better suited to a variety of workflows.

**Comment by Noorts** [comment]
Welcome back and thanks for the suggestion! I agree that this would indeed be very nice.

This has been on the roadmap for a while, in the following issue:
- #14 

The problem on the implementation side is that I don't want users to lose their current toggles when they update. So I'll see if I can find the time to dive into that.

Closing this issue, but keeping #14. Thanks again!
